# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paket SimPATI
email: info@paketsimpati.com
description: > # this means to ignore newlines until "baseurl:"
  Panduan Lengkap Pilihan Paket Termurah Kartu Sim<i>PATI</i> Telkomsel
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paketsimpati.github.io" # the base hostname & protocol for your site
twitter_username: SimPATI
github_username:  SimPATI

# Build settings
markdown: kramdown
